### ISSUE TITLE
Read-only file system error

### ISSUE THREAD

**Issue by andres-patrignani** [changliao1025/pyflowline#164]
Receiving error: `OSError: [Errno 30] Read-only file system: '/compyfs'` when running the following line in the Jupyter Notebook example:

`oPyflowline = pyflowline_read_model_configuration_file(sFilename_configuration_in, iCase_index_in=iCase_index, sMesh_type_in= sMesh_type, sDate_in=sDate)`

Library loads fine and code cells before this one return the correct output. Not sure whether this is an issue with the library, a file configuration in the example folder, or something in my local system.

**Comment by changliao1025** [comment]
Yes, the example provided in the repo was tested on our system, so you should change the paths to the actual path on your system. Hope that helps.

**Comment by andres-patrignani** [comment]
It helps and is in the notebook instructions. Editing all the paths by hand in the `*.json` files seems a bit overwhelming for a simple example, unless I'm missing something. Thanks for the prompt help.
